import {PGlite} from '@electric-sql/pglite';
import {beforeAll,afterAll,it,expect} from 'vitest';
import {readFileSync,readdirSync} from 'node:fs';
let db:PGlite,shop:string,plan:string;
const uid=(n:number)=>`30000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
async function user(n:number){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${uid(n)}',false);`);}
async function scalar<T=string>(sql:string,args:unknown[]=[]):Promise<T>{const r=await db.query<Record<string,T>>(sql,args);return Object.values(r.rows[0])[0];}
type Proposal={id:string;token:string;target:string};
const propose=(action='suspend_shop',target=shop,p:string|null=null)=>scalar<Proposal>('select public.platform_ai_propose($1,$2,$3)',[action,target,p]);
const decide=(p:Proposal,confirm=true)=>scalar<{ok:boolean;code?:string}>('select public.platform_ai_decide($1,$2,$3)',[p.id,p.token,confirm]);
beforeAll(async()=>{
 db=new PGlite();await db.exec(`create schema auth;create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon,service_role;grant execute on function auth.uid() to authenticated,anon,service_role;`);
 for(const f of readdirSync('supabase/migrations').sort())await db.exec(readFileSync('supabase/migrations/'+f,'utf8'));
 await db.query('insert into auth.users select unnest($1::uuid[])',[[1,2,3,99,98].map(uid)]);
 await user(1);shop=await scalar("select public.create_barbershop('Shop Secure','shop-secure','Owner One')");
 await db.exec('reset role');await db.query("insert into public.platform_admins(user_id,display_name) values($1,'Admin One'),($2,'Admin Two')",[uid(99),uid(98)]);
 await user(99);plan=await scalar("select id from public.saas_plans where code='PRO'");
});
afterAll(async()=>{await db?.close();});
it.each([1,2,3])('non-platform %s cannot propose or read alerts/usage',async n=>{await user(n);await expect(propose()).rejects.toThrow('FORBIDDEN');expect(await scalar<number>('select count(*)::int from public.platform_alerts')).toBe(0);expect(await scalar<number>('select count(*)::int from public.platform_ai_usage')).toBe(0);});
it('anon cannot access proposals or functions',async()=>{await db.exec('reset role;set role anon');await expect(propose()).rejects.toThrow('permission denied');await expect(db.query('select * from public.push_subscriptions')).rejects.toThrow('permission denied');});
it('proposal does not execute; raw text sim cannot confirm',async()=>{await user(99);const p=await propose();expect(await scalar('select platform_status from public.barbershops where id=$1',[shop])).toBe('active');await expect(db.query("select public.platform_ai_decide($1,$2,'sim')",[p.id,p.token])).rejects.toThrow();expect((await decide(p,false)).ok).toBe(true);});
it('allowed action executes once, creates audit and suspension alert',async()=>{await user(99);const p=await propose();expect((await decide(p)).ok).toBe(true);expect((await decide(p)).ok).toBe(false);expect(await scalar('select platform_status from public.barbershops where id=$1',[shop])).toBe('suspended');expect(await scalar<number>("select count(*)::int from public.audit_events where action='platform.ai.action_executed' and target_id=$1",[p.id])).toBe(1);expect(await scalar('select severity from public.platform_alerts where barbershop_id=$1',[shop])).toBe('warning');});
it('dedup repeated condition does not multiply alerts',async()=>{await user(99);await decide(await propose());expect(await scalar<number>('select count(*)::int from public.platform_alerts where barbershop_id=$1',[shop])).toBe(1);});
it('wrong actor and token rejected without consuming valid proposal',async()=>{await user(99);const p=await propose('reactivate_shop');await user(98);expect((await decide(p)).ok).toBe(false);await user(99);expect((await decide({...p,token:uid(1)})).ok).toBe(false);expect((await decide(p)).ok).toBe(true);});
it('expired proposal is rejected',async()=>{await user(99);const p=await propose();await db.exec('reset role');await db.query("update fio_private.ai_proposals set expires_at=now()-interval '1 minute' where id=$1",[p.id]);await user(99);expect((await decide(p)).ok).toBe(false);});
it('changed target state invalidates proposal',async()=>{await user(99);const p=await propose();await decide(await propose('change_plan',shop,plan));expect((await decide(p)).code).toBe('STATE_CHANGED');});
it('params and token are not writable or readable directly by admin',async()=>{await user(99);await expect(db.query("update fio_private.ai_proposals set params='{}'")).rejects.toThrow('permission denied');await expect(db.query('select token from fio_private.ai_proposals')).rejects.toThrow('permission denied');});
it.each(['delete_shop','delete_user','execute_sql','edit_rls'])('forbidden action %s',async action=>{await user(99);await expect(propose(action)).rejects.toThrow('FORBIDDEN');});
it('alert resolution is authorized and audited',async()=>{await user(99);await decide(await propose());const id=await scalar('select id from public.platform_alerts where barbershop_id=$1',[shop]);const p=await propose('resolve_alert',id);expect((await decide(p)).ok).toBe(true);expect(await scalar('select resolved_by from public.platform_alerts where id=$1',[id])).toBe(uid(99));});
it('quota is durable; denied requests audit without rollback',async()=>{await user(98);for(let i=0;i<10;i++)expect(await scalar<boolean>('select public.consume_platform_ai_quota()')).toBe(true);expect(await scalar<boolean>('select public.consume_platform_ai_quota()')).toBe(false);expect(await scalar<number>("select count(*)::int from public.audit_events where action='platform.ai.rate_limit'")).toBeGreaterThan(0);});
it('push is opt-in: no subscriptions means no delivery',async()=>{await db.exec('reset role');expect(await scalar<number>('select count(*)::int from fio_private.push_deliveries')).toBe(0);});
it('push endpoint belongs only to actor and non-platform cannot register',async()=>{await user(1);await expect(db.query("insert into public.push_subscriptions(user_id,endpoint,keys) values($1,'https://fcm.googleapis.com/a','{}')",[uid(1)])).rejects.toThrow('row-level security');await user(99);await db.query("insert into public.push_subscriptions(user_id,endpoint,keys,warning) values($1,'https://fcm.googleapis.com/test','{}',true)",[uid(99)]);await user(98);expect(await scalar<number>('select count(*)::int from public.push_subscriptions')).toBe(0);});
it('push queue creates one delivery, leases once and cleans expired subscription',async()=>{await user(99);await decide(await propose('reactivate_shop'));await decide(await propose());await expect(db.query('select public.platform_claim_push()')).rejects.toThrow('permission denied');await db.exec('reset role;set role service_role');const d=await scalar<{alertId:string;subscriptionId:string}[]>('select public.platform_claim_push()');expect(d).toHaveLength(1);expect(await scalar('select public.platform_claim_push()')).toEqual([]);await db.query("select public.platform_finish_push($1,$2,'expired')",[d[0].alertId,d[0].subscriptionId]);await user(99);expect(await scalar<number>('select count(*)::int from public.push_subscriptions')).toBe(0);});
it('revoked platform admin cannot confirm',async()=>{await user(99);const p=await propose('reactivate_shop');await db.exec('reset role');await db.query('update public.platform_admins set active=false where user_id=$1',[uid(99)]);await user(99);await expect(decide(p)).rejects.toThrow('FORBIDDEN');});
it('repeated AI errors generate one critical deterministic alert',async()=>{await user(98);for(let i=0;i<4;i++)await db.query("select public.platform_ai_audit('error',$1,'request_failed')",[uid(i+1)]);expect(await scalar<number>("select count(*)::int from public.platform_alerts where type='ai_failures' and severity='critical'")).toBe(1);});
it('changing to a plan disabled after proposal is refused and audited',async()=>{await user(98);const free=await scalar("select id from public.saas_plans where code='FREE'");const p=await propose('change_plan',shop,free);await db.exec('reset role');await db.query('update public.saas_plans set active=false where id=$1',[free]);await user(98);expect((await decide(p)).code).toBe('ACTION_REFUSED');expect(await scalar<number>("select count(*)::int from public.audit_events where target_id=$1 and action='platform.ai.action_refused'",[p.id])).toBe(1);});
it('push opt-in preferences exclude critical messages when disabled',async()=>{await user(98);await db.query("insert into public.push_subscriptions(user_id,endpoint,keys,critical,warning,info) values($1,'https://fcm.googleapis.com/no-critical','{}',false,false,false)",[uid(98)]);await db.exec('reset role');await db.query("insert into public.platform_alerts(type,severity,title,description,dedup_key) values('test','critical','Critical test','Test','test-critical')");expect(await scalar<number>('select count(*)::int from fio_private.push_deliveries')).toBe(0);});
