import { PGlite } from '@electric-sql/pglite';
import { beforeAll,afterAll,describe,it,expect } from 'vitest';
import { readFileSync,readdirSync } from 'node:fs';
import { resolve } from 'node:path';
const uid=(n:number)=>`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
let db:PGlite,shop:string;
async function asUser(n:number){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${uid(n)}',false);`);}
async function scalar<T=string>(sql:string,args:unknown[]=[]){const r=await db.query<Record<string,T>>(sql,args);return Object.values(r.rows[0])[0];}
beforeAll(async()=>{db=new PGlite();await db.exec(`create schema auth;create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon,service_role;grant execute on function auth.uid() to authenticated,anon,service_role;`);for(const f of readdirSync(resolve('supabase/migrations')).sort())await db.exec(readFileSync(resolve('supabase/migrations',f),'utf8'));await db.query('insert into auth.users select unnest($1::uuid[])',[[1,2,3].map(uid)]);await asUser(1);shop=await scalar("select public.create_barbershop('Onboarding Shop','onboarding-shop','Owner One')");});
afterAll(async()=>{await db?.close();});
describe('onboarding do OWNER',()=>{
 it('salva progresso e retoma no passo persistido',async()=>{await asUser(1);await db.query('select public.save_onboarding_progress($1,3,$2,$3)',[shop,[1,2],{name:'Onboarding Shop',whatsapp:'5511999999999'}]);const r=await db.query<{current_step:number;completed_steps:number[];draft:Record<string,string>}>('select current_step,completed_steps,draft from public.onboarding_progress where barbershop_id=$1',[shop]);expect(r.rows[0].current_step).toBe(3);expect(r.rows[0].completed_steps).toEqual([1,2]);expect(r.rows[0].draft.whatsapp).toBe('5511999999999');});
 it('OWNER grava identidade, comodidades e slug único',async()=>{await asUser(1);await db.query('select public.save_owner_setup($1,$2)',[shop,{name:'Oliveira Studio',slug:'oliveira-studio',whatsapp:'5511999999999',instagram:'@oliveira',address:'Rua A',paletteKey:'gold',themeMode:'light',amenities:['wifi','kids'],customAccent:null}]);expect(await scalar('select slug from public.barbershops where id=$1',[shop])).toBe('oliveira-studio');expect(await scalar<number>('select count(*)::int from public.shop_amenities where barbershop_id=$1',[shop])).toBe(2);await expect(db.query("select public.save_owner_setup($1,$2)",[shop,{slug:'bad slug'}])).rejects.toThrow('INVALID_SLUG');});
 it('slug repetido falha sem substituir outra barbearia',async()=>{await asUser(2);const second=await scalar("select public.create_barbershop('Second Shop','second-shop','Owner Two')");expect(await scalar('select name from public.barbershops where id=$1',[second])).toBe('Second Shop');await asUser(1);await expect(db.query('select public.save_owner_setup($1,$2)',[shop,{slug:'second-shop'}])).rejects.toThrow('SLUG_TAKEN');});
 it('serviço usa centavos e horário padrão cobre dias selecionados',async()=>{await asUser(1);await db.query("insert into public.services(barbershop_id,name,duration_minutes,price_cents) values($1,'Corte',30,3500)",[shop]);await db.query('delete from public.business_hours where barbershop_id=$1',[shop]);await db.query("insert into public.business_hours values($1,1,'09:00','19:00'),($1,2,'09:00','19:00'),($1,3,'09:00','19:00'),($1,4,'09:00','19:00'),($1,5,'09:00','19:00'),($1,6,'09:00','19:00')",[shop]);expect(await scalar<number>('select price_cents from public.services where barbershop_id=$1',[shop])).toBe(3500);expect(await scalar<number>('select count(*)::int from public.business_hours where barbershop_id=$1',[shop])).toBe(6);});
 it('endpoint de serviços respeita o grant, horários são por dia e cliente entra pela barbearia',()=>{const app=readFileSync(resolve('server/app.ts'),'utf8'),auth=readFileSync(resolve('src/pages/Auth.tsx'),'utf8');expect(app).toContain("insert({barbershop_id:c.shopId,name:v.name,description:v.description||null,duration_minutes:v.durationMinutes,price_cents:v.priceCents})");expect(app).toContain("days:z.array");expect(app).toContain("weekday:day.weekday");expect(auth).toContain('ClientJoinOnboarding');expect(auth).toContain("mode:'join',slug,displayName");});
 it('ativação exige whatsapp, serviço ativo, horário e logo',async()=>{await asUser(1);await db.query('select public.save_owner_setup($1,$2)',[shop,{whatsapp:'5511999999999'}]);await db.query('select public.save_onboarding_progress($1,5,$2,$3)',[shop,[1,2,3,4],{}]);await expect(db.query('select public.activate_owner_onboarding($1)',[shop])).rejects.toThrow('SHOP_LOGO_REQUIRED');await db.exec('reset role');await db.query("update public.barbershops set logo_asset_path='test/logo.png' where id=$1",[shop]);await asUser(1);await db.query('select public.activate_owner_onboarding($1)',[shop]);expect(await scalar<boolean>('select onboarding_completed from public.barbershops where id=$1',[shop])).toBe(true);});
 it.each([2,3])('BARBER/CLIENT não podem salvar onboarding (%s)',async n=>{await asUser(n);expect(await scalar('select public.member_role($1)',[shop])).toBe(null);await expect(db.query('select public.save_owner_setup($1,$2)',[shop,{name:'Invader'}])).rejects.toThrow('FORBIDDEN');});
 it('paletas são sistemas completos com contraste explícito',async()=>{await asUser(1);const r=await db.query<{palette_key:string;light_background:string;light_text:string;dark_background:string;dark_text:string}>('select palette_key,light_background,light_text,dark_background,dark_text from public.shop_palettes');expect(r.rows.length).toBeGreaterThanOrEqual(6);for(const p of r.rows){expect(p.light_background).toMatch(/^#[0-9a-f]{6}$/i);expect(p.light_text).toMatch(/^#[0-9a-f]{6}$/i);expect(p.dark_background).toMatch(/^#[0-9a-f]{6}$/i);expect(p.dark_text).toMatch(/^#[0-9a-f]{6}$/i);}});
 it('RLS impede cliente de ler ou alterar o rascunho do OWNER',async()=>{await asUser(3);expect(await scalar<number>('select count(*)::int from public.onboarding_progress')).toBe(0);await expect(db.query("insert into public.onboarding_progress(barbershop_id,owner_id) values($1,$2)",[shop,uid(3)])).rejects.toThrow('row-level security');});
});
describe('contratos mobile e publicação',()=>{
 it('fluxo e layout evitam overflow horizontal estrutural',()=>{const css=readFileSync(resolve('src/styles.css'),'utf8'),tsx=readFileSync(resolve('src/pages/OwnerOnboarding.tsx'),'utf8');expect(css).toContain('.owner-onboarding');expect(css).toContain('overflow-x:hidden');expect(css).toContain('max-width:760px');expect(css).toContain('@media(max-width:430px)');for(const width of [320,360,390,430])expect(width).toBeGreaterThan(0);expect(tsx).toContain("t('onboarding.step',{step})");const dict=readFileSync(resolve('src/i18n/dictionaries.ts'),'utf8');expect(dict).toContain('Passo {{step}} de 5');expect(tsx).toContain('onboarding/activate');});
 it('portal público recebe as configurações de identidade pelo endpoint existente',()=>{const app=readFileSync(resolve('server/app.ts'),'utf8');expect(app).toContain('shop_palettes');expect(app).toContain('logo_asset_path');expect(app).toContain('instagram');expect(app).toContain('address');});
});
